server:
  port: 9090

  servlet:
    context-path: /jk
api:
  version: 1.0

swagger:
  enabled: true
  title: explore
  description: Sample Swagger implementation for exploring java and spring boot.
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false
